### ISSUE TITLE
Error: Refusing to delete c:\chef\payload\__project__\node_modules\.bin\mime: is outside c:\chef\payload\__project__\node_modules\mime and not a link

### ISSUE THREAD

**Issue by anh65498** [saucelabs/saucectl-cypress-example#14]
Hi everyone,
I'm trying to run my Cypress Cucumber tests in sauce mode on different browser versions. I have tried both command `saucectl run`  and `saucectl run --tunnel-id <my tunnel id>`  but I'm getting this error

```
Error: Refusing to delete c:\chef\payload\__project__\node_modules\.bin\mime: is outside c:\chef\payload\__project__\node_modules\mime and not a link
      at clobberFail (D:\sauce-cypress-runner\7.1.1\bundle\node_modules\npm\node_modules\gentle-fs\lib\rm.js:121:12)
      at isSafeToRm (D:\sauce-cypress-runner\7.1.1\bundle\node_modules\npm\node_modules\gentle-fs\lib\rm.js:114:15)
      at D:\sauce-cypress-runner\7.1.1\bundle\node_modules\npm\node_modules\gentle-fs\lib\rm.js:54:5
      at LOOP (D:\sauce-cypress-runner\7.1.1\bundle\node_modules\npm\node_modules\slide\lib\chain.js:7:26)
      at D:\sauce-cypress-runner\7.1.1\bundle\node_modules\npm\node_modules\slide\lib\chain.js:18:7
      at D:\sauce-cypress-runner\7.1.1\bundle\node_modules\npm\node_modules\gentle-fs\lib\rm.js:180:7
      at D:\sauce-cypress-runner\7.1.1\bundle\node_modules\npm\node_modules\gentle-fs\node_modules\iferr\index.js:13:50
      at _readAllLinks (D:\sauce-cypress-runner\7.1.1\bundle\node_modules\npm\node_modules\gentle-fs\lib\rm.js:215:28)
      at D:\sauce-cypress-runner\7.1.1\bundle\node_modules\npm\node_modules\gentle-fs\node_modules\iferr\index.js:13:50
      at resolveSymlink (D:\sauce-cypress-runner\7.1.1\bundle\node_modules\npm\node_modules\gentle-fs\lib\rm.js:226:22)
      at _readAllLinks (D:\sauce-cypress-runner\7.1.1\bundle\node_modules\npm\node_modules\gentle-fs\lib\rm.js:217:5)
      at readAllLinks (D:\sauce-cypress-runner\7.1.1\bundle\node_modules\npm\node_modules\gentle-fs\lib\rm.js:212:3)
      at D:\sauce-cypress-runner\7.1.1\bundle\node_modules\npm\node_modules\gentle-fs\lib\rm.js:179:5
      at D:\sauce-cypress-runner\7.1.1\bundle\node_modules\npm\node_modules\gentle-fs\node_modules\iferr\index.js:13:50
      at cb (D:\sauce-cypress-runner\7.1.1\bundle\node_modules\npm\node_modules\slide\lib\async-map.js:47:24)
      at D:\sauce-cypress-runner\7.1.1\bundle\node_modules\npm\node_modules\gentle-fs\lib\rm.js:153:16
      at _readAllLinks (D:\sauce-cypress-runner\7.1.1\bundle\node_modules\npm\node_modules\gentle-fs\lib\rm.js:215:28)
      at D:\sauce-cypress-runner\7.1.1\bundle\node_modules\npm\node_modules\gentle-fs\node_modules\iferr\index.js:13:50
      at resolveSymlink (D:\sauce-cypress-runner\7.1.1\bundle\node_modules\npm\node_modules\gentle-fs\lib\rm.js:226:22)
      at _readAllLinks (D:\sauce-cypress-runner\7.1.1\bundle\node_modules\npm\node_modules\gentle-fs\lib\rm.js:217:5)
      at readAllLinks (D:\sauce-cypress-runner\7.1.1\bundle\node_modules\npm\node_modules\gentle-fs\lib\rm.js:212:3)
      at D:\sauce-cypress-runner\7.1.1\bundle\node_modules\npm\node_modules\gentle-fs\lib\rm.js:156:8 {
    code: 'EEXIST',
    path: 'c:\\chef\\payload\\__project__\\node_modules\\.bin\\cypress-tags'
  },
  code: 'EEXIST',
  path: 'c:\\chef\\payload\\__project__\\node_modules\\.bin\\cypress-tags',
  parent: '__project__'
```

My React server is up and runing. Sauce Connect tunnel is also up and running too. Here's the execution URL: https://app.eu-central-1.saucelabs.com/tests/ec85ef2db9344d849fd32cba1bebd6ba

**Comment by alexplischke** [comment]
Hm. May I see the contents of the `.sauceignore` file?

**Comment by anh65498** [comment]
I added `package.json` to `.sauceignore` and that solved the problem. Thanks Alex
